# Generated by Django 5.2.12 on 2026-04-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_change_visit_id_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSessionStatus',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('participant_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('opportunity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped (no questions matched)')], default='processed', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('answer_rows_created', models.IntegerField(default=0)),
                ('llm_calls_made', models.IntegerField(default=0)),
                ('session_created_at', models.DateTimeField(blank=True, help_text='From OCS session.created_at', null=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews_session_status',
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('participant_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('qid', models.CharField(db_index=True, help_text="e.g. 'A.1', 'A.5b'", max_length=32)),
                ('parent_qid', models.CharField(db_index=True, help_text="e.g. 'A.1', 'A.5'", max_length=32)),
                ('question_text', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=128)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('asked', models.BooleanField(default=True, help_text='Was this question offered in the session?')),
                ('completed', models.BooleanField(default=False, help_text='Did the FLW give a substantive answer?')),
                ('num_turns', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('time_to_answer_seconds', models.FloatField(blank=True, null=True)),
                ('extraction_method', models.CharField(help_text="'word_overlap' for single-part, 'llm' for multi-part", max_length=32)),
                ('opportunity_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cohort_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews_answer',
                'indexes': [models.Index(fields=['opportunity_id', 'completed'], name='interviews__opportu_0a5107_idx'), models.Index(fields=['cohort_name', 'completed'], name='interviews__cohort__a3e82c_idx'), models.Index(fields=['participant_id', 'completed'], name='interviews__partici_2ee6f4_idx')],
                'unique_together': {('session_id', 'qid')},
            },
        ),
    ]
