# Generated by Django 5.2.12 on 2026-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_interviewsessionstatus_interviewanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='computed_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Step 2-6 derived fields (scoring, typologies, etc.)'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='experiment_id',
            field=models.CharField(blank=True, db_index=True, help_text='OCS bot UUID — supports multi-bot in future', max_length=64),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='pipeline_version',
            field=models.CharField(db_index=True, default='1.0', help_text='Bump when prompts/algorithm change to keep historical results', max_length=32),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='questions_version',
            field=models.CharField(blank=True, help_text="Identifier for the questions file used (e.g. 'round3_expanded')", max_length=32),
        ),
        migrations.AddField(
            model_name='interviewsessionstatus',
            name='experiment_id',
            field=models.CharField(blank=True, db_index=True, help_text='OCS bot UUID this session belongs to', max_length=64),
        ),
        migrations.AddField(
            model_name='interviewsessionstatus',
            name='pipeline_version',
            field=models.CharField(db_index=True, default='1.0', max_length=32),
        ),
        migrations.AddField(
            model_name='interviewsessionstatus',
            name='total_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsessionstatus',
            name='total_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='interviewanswer',
            unique_together={('session_id', 'qid', 'pipeline_version')},
        ),
        migrations.AddIndex(
            model_name='interviewanswer',
            index=models.Index(fields=['experiment_id', 'pipeline_version'], name='interviews__experim_f59f29_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsessionstatus',
            index=models.Index(fields=['experiment_id', 'session_created_at'], name='interviews__experim_a13ca0_idx'),
        ),
    ]
